### ISSUE TITLE
似乎只能产生很少的字符

### ISSUE THREAD

**Issue by andeyeluguo** [lyogavin/Anima#115]
好像只能产生几个字符,再多的话花费时间太久了

**Comment by andeyeluguo** [comment]
只能说可以体验下

**Comment by lyogavin** [comment]
长度多少都可以 速度的话肯定不快 

需要快的话 还是得比较强的GPU

不是为实时的场景设计的 比较适合不需要实时响应的场景。比如一些离线数据分析的场景，比如我们有一些场景可以跑一晚上出结果就行。
