### ISSUE TITLE
协议要求是什么，有哪些限制？

### ISSUE THREAD

**Issue by wzg-zhuo** [lyogavin/Anima#13]

**Comment by lyogavin** [comment]
license都可以在huggingface找到：
adaptor model 是apache 2.0。最开放的。
merged model因为基于llama，license是llama的license。

**Comment by penghanyuan** [comment]
你好，我在Guanaco 的页面看见：_“Guanaco adapter weights are available under Apache 2 license. Note the use of the Guanaco adapter weights, requires access to the LLaMA model weighs. Guanaco is based on LLaMA and therefore should be used according to the LLaMA license.”_
如果我理解没错的话，Anima的adaptor model如果也是基于Guanaco的weight训练的话应该也是要遵守llama的license吧？（而不是apache 2.0）？

感谢指教。

> license都可以在huggingface找到： adaptor model 是apache 2.0。最开放的。 merged model因为基于llama，license是llama的license。

**Comment by lyogavin** [comment]
是的 如果merged的话应该还是需要遵守LLAMA license

**Comment by penghanyuan** [comment]
> 

感谢回复，所以您之前说的_“adaptor model 是apache 2.0。最开放的。”_ 说明这个adaptor model的版本的训练是from scratch的对吧 ?
