### ISSUE TITLE
请问有没有稳定中文输出的办法？

### ISSUE THREAD

**Issue by AIchenkai** [lyogavin/Anima#16]
现在这个版本输出经常输出英文，即使是用中文提的问题。
有什么办法稳定中文的输出吗？

**Comment by lyogavin** [comment]
> 现在这个版本输出经常输出英文，即使是用中文提的问题。 有什么办法稳定中文的输出吗？

可以在prompt里边加入：请用中文回答。会好很多。

**Comment by lyogavin** [comment]
> 词表还是用的LLAMA的,只有32000,应该需要扩充词表

我觉得transformer不需要用传统的NLP分词思维去理解，transformer没什么词表的概念。
如果是embedding projection matrix 没见过一些生字，可能扩展到更多的字可能会好一点。还不确定。后边有时间的话可以做一些实验。
