### ISSUE TITLE
Reference一定要和base一致吗

### ISSUE THREAD

**Issue by BillKiller** [lyogavin/Anima#17]
Reference模型如果使用大模型，base模型使用小模型能够让模型学习到reference的特征吗？

**Comment by lyogavin** [comment]
现在reference model有两个作用，一个是作为initial model，另一个是作为DPO optmization时候的reference 计算KL散度，保证优化结果不会偏离太远。

第一个的话需要保持两个模型一致的。
第二个理论上讲可以不一样。
