### ISSUE TITLE
fine-tuning QLoRA on other base models

### ISSUE THREAD

**Issue by RanchiZhao** [lyogavin/Anima#2]
Thank you for your work! I wonder if there is any experience with fine-tuning QLoRA on other base models? I'm not sure if most of the base models on Huggingface would perform well? Especially for chinese.

**Comment by lyogavin** [comment]
I think so theoretically. As QLoRA is just a way to optimize the memory consumption during the optimization. In terms of model performance it should be as effective as LORA/AdaLORA. There are lots of papers evaluated the performance of LORA/AdaLORA/PTurning/Prefix Tuning, etc.

We'll publish more experiments results later in this repro.
