### ISSUE TITLE
Adapter模型的合并

### ISSUE THREAD

**Issue by LiuChen19960902** [lyogavin/Anima#20]
这是一个非常nice的工作。
这里我有个小问题想请教一下：
如题，Anima33B的adapter model是和原始的LLama合并后得到Anima33B merged嘛

**Comment by lyogavin** [comment]
原始model是基于Guanaco。是adapter和Guanaco merge的。

**Comment by gjm441** [comment]
merged 模型是基于原始的Guanaco fp32模型和apdapter (B*A)之后的结果吗？推理可以使用merged 模型，加载使用nf4方式来推理吗？

> 原始model是基于Guanaco。是adapter和Guanaco merge的。
