### ISSUE TITLE
peft版本问题："addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by liuyeah** [lyogavin/Anima#23]
您好，这是个非常好的工作！但我inference阶段：

generate_ids = model.generate(**inputs, max_new_tokens=30)

时遇到报错：

"addmm_impl_cpu_" not implemented for 'Half'.

这边感觉应该是peft和transformers版本问题？我这边使用的版本如下：

transformers：4.31.0.dev0
peft：0.4.0.dev0

想问下您那边的transformers和peft版本是？

非常感谢！

**Comment by lyogavin** [comment]
我好像碰到过。好像是哪一个package的版本问题。

有完整的stack吗？

**Comment by lyogavin** [comment]
这个问题应该是cuda驱动安装有问题吧？检查一下：nvidia-smi输出什么？


可以参考：
https://stackoverflow.com/q/73530569/21230266
