### ISSUE TITLE
使用lyogavin/Anima33B-DPO-Belle-1k-merged模型推断时大量重复

### ISSUE THREAD

**Issue by xiu-ze** [lyogavin/Anima#24]
非常感谢您在DPO上的工作！我在使用[lyogavin/Anima33B-DPO-Belle-1k-merged](https://huggingface.co/lyogavin/Anima33B-DPO-Belle-1k-merged)模型做推断的时候，产生了结尾重复现象（在推断的时候尝试了3种模板，但都很容易有重复现象），希望帮忙解答一下问题所在。下面会贴出我使用的推断样例、推断代码。

一、推断样例
因为不确定使用DPO模型推断的模版是什么，所以在推断的时候尝试了三种模板：1.直接提问；2.参考DPO训练时的模板；3.`test_cn_dataset_lenghts.py`[文件]((https://github.com/lyogavin/Anima/blob/main/scripts/test_cn_dataset_lenghts.py))中的source_template。
> 输入：世界上最长的河流是什么？
> 输出：世界上最长的河是尼罗河。它从埃及到埃塞俄比亚流经了非洲大陆，长约6650公里。它是世界上最长、最宽、最深、最漫长、最湿润、最有生态产生力的河。它汇集了埃及、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比
---- 
> 输入：\n\nHuman: 世界上最长的河流是什么？\n\nAssistant: 
> 输出：世界上最长的河流是尼罗河。它从非洲的乌吉亚高原开始，流经非洲和欧洲，最终流入埃及的瓦丽纳盆地。它的长度约为6650公里。尼罗河汇集了非洲和欧洲的多个河流，汇集了很多水资源，是非洲和欧洲最重要的河流之一。尼罗河汇集了埃及、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞俄比亚、苏丹、埃塞�
---- 
> 输入：Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\n世界上最长的河流是什么？\n\n### Response: 
> 输出：世界上最长的河流是尼罗河。它从埃及的狮子山源头开始，流经埃及、苏丹、肯尼亚、埃塞俄比亚、苏丹、埃塞俄比亚、肯尼亚、埃塞俄比亚、苏丹、埃塞俄比亚、肯尼亚、埃塞俄比亚、苏丹、埃塞俄比亚、肯尼亚、埃塞俄比亚、苏丹、埃塞俄比亚、肯尼亚、埃塞俄比亚、苏丹、埃塞俄比亚、肯尼亚、埃塞俄比亚、苏丹、埃塞俄比亚、肯尼亚、埃塞俄比亚、苏丹、埃塞俄比亚、肯尼亚、埃塞俄比亚、苏丹、埃塞俄比亚、肯尼亚、埃塞俄比亚、苏丹、埃塞俄比亚、肯尼亚、埃塞俄比亚、苏丹、埃塞俄比亚、肯尼亚、��

二、推断代码
```python
# imports
import torch
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
from peft import PeftModel
from transformers import GenerationConfig, LlamaForCausalLM, LlamaTokenizer
import json
from tqdm import tqdm

# create tokenizer
base_model = "Anima33B-DPO-Belle-1k-merged"
tokenizer = LlamaTokenizer.from_pretrained(base_model)

# base model
model = LlamaForCausalLM.from_pretrained(
        base_model,
        torch_dtype=torch.float16,
        device_map="auto",
    )

model.eval()

prompt = input("")
inputs = tokenizer(prompt, return_tensors="pt")
generate_ids = model.generate(**inputs, max_new_tokens=512)

print(tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0])
```

**Comment by lyogavin** [comment]
可以试试调整一下generation的参数，比如把repetition_penalty开强一些，应该会好很多

可以参考下边这个：

    temperature=0.001,
    top_k=30,
    top_p=0.85,
    do_sample=True,
    num_beams=1,
    repetition_penalty=1.2,

**Comment by xiu-ze** [comment]
感谢您的解答，测了几个case，生成结果确实好了不少。请问训练的时候采用类似于[hh-rlhf数据集](https://huggingface.co/datasets/Anthropic/hh-rlhf)的格式，那推断的时候是不是应该也按这个格式推断啊？

**Comment by lyogavin** [comment]
> 感谢您的解答，测了几个case，生成结果确实好了不少。请问训练的时候采用类似于[hh-rlhf数据集](https://huggingface.co/datasets/Anthropic/hh-rlhf)的格式，那推断的时候是不是应该也按这个格式推断啊？

保持一致应该好一点。可以测试一下。
