### ISSUE TITLE
如何支持超长文本的训练？

### ISSUE THREAD

**Issue by rookielyb** [lyogavin/Anima#35]
我的理解是 用来训练超长文本的策略优化都在 modeling_flash_llama文件里 ，但是训练的 longer_training 文件中没有体现modeling_flash_llama里的内容啊  模型结构加载的还是原来的结构  没有替换成 modeling_flash_llama里改的结构  这个地方有些不太理解，希望解答一下，谢谢！

**Comment by lyogavin** [comment]
trick在这里：from_pretrained()里边有一个参数：trust_remote_code，打开这个HF会允许你在repo里边加入你自己的module code
