### ISSUE TITLE
The model precision used for training with qlora

### ISSUE THREAD

**Issue by Nipi64310** [lyogavin/Anima#43]
Hey @lyogavin ,thanks a lot for sharing this awesome job! 
I've got a silly question to ask. When using qlora to train a model, is it possible to load either the normal or quantized base model? Both seem to train fine, but it appears that loading the unquantized base model trains a bit faster. I was wondering if there are any differences between the models trained in these two modes.

**Comment by Nipi64310** [comment]
> if the question is about the difference between LORA training and normal training, LORA should be much faster as much fewer parameters need to be transfered in memory, which is the slowest part of training.

Sorry, I didn't explain clearly. Let me give you an example. In the script "Anima/training/run_Amina_training.sh", the default value for the "model_name_or_path" parameter is "timdettmers/guanaco-33b-merged".

But here's what I found: you can actually use either "01-ai/Yi-34B-Chat" or "01-ai/Yi-34B-Chat-4bits" as the value for the "model_name_or_path" parameter. And interestingly, both the 4-bit and fp16 base models work fine with this script. So my question is, what's the difference between using base models with different precisions?

Another interesting discovery is that the lora weights obtained from finetuning with "01-ai/Yi-34B-Chat" can be used with the quantized model "01-ai/Yi-34B-Chat-4bits" during inference, and the results are also normal.

**Comment by lyogavin** [comment]
the 4bit in QLORA is mainly about the storage data type for forward and backward passes of training.

I think 01-ai/Yi-34B-Chat-4bits is mainly quantized for speeding up the inference instead of training.
