### ISSUE TITLE
max() arg is an empty sequence

### ISSUE THREAD

**Issue by Minami-su** [lyogavin/Anima#52]
```
from airllm import AirLLMLlama2

MAX_LENGTH = 128
# could use hugging face model repo id:
#model = AirLLMLlama2("garage-bAInd/Platypus2-70B-instruct")
model = AirLLMLlama2("Qwen-14B-Chat",
                     compression='4bit' # specify '8bit' for 8-bit block-wise quantization "Yi-34B-Chat",
                    )
# or use model's local path...
#model = AirLLMLlama2("/home/ubuntu/.cache/huggingface/hub/models--garage-bAInd--Platypus2-70B-instruct/snapshots/b585e74bcaae02e52665d9ac6d23f4d0dbc81a0f")

input_text = [
        'What is the capital of United States?',
        #'I like',
    ]

input_tokens = model.tokenizer(input_text,
    return_tensors="pt", 
    return_attention_mask=False, 
    truncation=True, 
    max_length=MAX_LENGTH, 
    padding=True)
           
generation_output = model.generate(
    input_tokens['input_ids'].cuda(), 
    max_new_tokens=20,
    use_cache=True,
    return_dict_in_generate=True)

output = model.tokenizer.decode(generation_output.sequences[0])

print(output)
```
>>>> bitsandbytes installed
>>>> bitsandbytes installed
>>>> bitsandbytes installed
  0%|                                                                                             | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/luhao/air22.py", line 6, in <module>
    model = AirLLMLlama2("Qwen-14B-Chat",
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/airllm/airllm.py", line 75, in __init__
    self.model_local_path, self.checkpoint_path = find_or_create_local_splitted_path(model_local_path_or_repo_id,
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/airllm/utils.py", line 276, in find_or_create_local_splitted_path
    return Path(model_local_path_or_repo_id), split_and_save_layers(model_local_path_or_repo_id, layer_shards_saving_path,
  File "/root/anaconda3/envs/train/lib/python3.9/site-packages/airllm/utils.py", line 220, in split_and_save_layers
    if max(shards) > shard:
ValueError: max() arg is an empty sequence

**Comment by lyogavin** [comment]
You have to use AirLLMChatGLM instead of AirLLMLlama2, GLM implementation is a little different. So have to use another class like below:

`from airllm import AirLLMChatGLM`

We'll consolidate them a little to make it a bit easier to use.
