### ISSUE TITLE
qwen报错

### ISSUE THREAD

**Issue by lymanzhao** [lyogavin/Anima#59]
如图，完全没有头绪
![Clipboard 1](https://github.com/lyogavin/Anima/assets/8308505/70d68321-4fe0-43c3-8bea-3b5db42d017e)

**Comment by lymanzhao** [comment]
磁盘足够的，还有2T呢

**Comment by lymanzhao** [comment]
flashattention没有装，我的2080核心太老，官网的代码能跑就是慢

**Comment by lyogavin** [comment]
能把你的代码贴一下吗？

**Comment by Sandwiches97** [comment]
同样是这个报错，chatglm3

**Comment by Sandwiches97** [comment]
> 同样是这个报错，chatglm3



`python

from airllm import AirLLMChatGLM

MAX_LENGTH = 128
# could use hugging face model repo id:
# model = AirLLMLlama2("garage-bAInd/Platypus2-70B-instruct")

# or use model's local path...
model = AirLLMChatGLM("/home/aurora/model/chatglm3-6b", 
                     layer_shards_saving_path="/home/aurora/model/chatglm3-layer")
`

**Comment by lyogavin** [comment]
Thanks, checking...

**Comment by lyogavin** [comment]
> 同样是这个报错，自定义保存路径，加载chatglm3
> 
> ```python
> from airllm import AirLLMChatGLM
> 
> MAX_LENGTH = 128
> # could use hugging face model repo id:
> # model = AirLLMLlama2("garage-bAInd/Platypus2-70B-instruct")
> 
> # or use model's local path...
> model = AirLLMChatGLM("/home/aurora/model/chatglm3-6b", 
>                      layer_shards_saving_path="/home/aurora/model/chatglm3-layer")
> ```

奇怪 同样的代码我这里是可以的。
1, 这个layer_shards_saving_path是soft link吗？
2, airllm pip 版本是多少？

**Comment by lyogavin** [comment]
I still can't reproduce.

I doubt it's some files are not saved correctly, or there might be some corruptions or failed downloaded files.

I added some auto validations and auto re-save logic in airllm==2.4.1 in 471a83dd4d08b4d539e6606b4b21b4bd580a1932.

Please upgrade airllm and rerun to try again. Thanks.

**Comment by lyogavin** [comment]
> > I still can't reproduce.
> > I doubt it's some files are not saved correctly, or there might be some corruptions or failed downloaded files.
> > I added some auto validations and auto re-save logic in airllm==2.4.1 in [471a83d](https://github.com/lyogavin/Anima/commit/471a83dd4d08b4d539e6606b4b21b4bd580a1932).
> > Please upgrade airllm and rerun to try again. Thanks.
> 
> Thanks, airllm==2.4.1 works ! great jobs ! When max_new_tokens is set to a larger value （e.g. 256）, the inference is a bit slow. It seems that only one layer is loaded into the GPU memory for calculation each time? Is it possible to load a customized number of layers into the GPU memory for calculation each time? ( In other words, when saving model layers, save multiple layers into one safetensors file at once?)

We are working on further improving the inference time. And let's use #44 to continue the discussion.
