### ISSUE TITLE
cant initial NVML.... No CUDA GPUs are available

### ISSUE THREAD

**Issue by hiqsociety** [lyogavin/Anima#72]
cant initial NVML.... No CUDA GPUs are available

how to resolve this?

**Comment by lyogavin** [comment]
do you have nvidia GPU?

**Comment by lyogavin** [comment]
we only support gpu

**Comment by hiqsociety** [comment]
@lyogavin yes i have nvidia. can you do a version in docker? because i have no idea why it's not detecting

**Comment by lyogavin** [comment]
> @lyogavin yes i have nvidia. can you do a version in docker? because i have no idea why it's not detecting

I see. It sounds like it has something to do with your CUDA driver/toolkits installations.

How's `torch.cuda.is_available()` ?
