### ISSUE TITLE
RuntimeError: expected scalar type struct c10::Half but found double

### ISSUE THREAD

**Issue by quifas** [lyogavin/Anima#73]
`from torch.fx import symbolic_trace     
from airllm import AirLLMQWen
MAX_LENGTH = 128
model = AirLLMQWen("Qwen/Qwen-7B")
input_text = ['What is the capital of China?',]
input_tokens = model.tokenizer(input_text,
    return_tensors="pt",
    return_attention_mask=False,
    truncation=True,
    max_length=MAX_LENGTH)
generation_output = model.generate(
    input_tokens['input_ids'].cuda(),
    max_new_tokens=5,
    use_cache=True,
    return_dict_in_generate=True)
model.tokenizer.decode(generation_output.sequences[0])`

出现以下问题：  
File "...cache\huggingface\modules\transformers_modules\ffe04dd57f85293043ba999a2c0daa788d6182e9\modeling_qwen.py", line 352, in _attn
    attn_weights = torch.where(
RuntimeError: expected scalar type struct c10::Half but found double

torch：1.10.2+cu102

请问怎么解决？

**Comment by lyogavin** [comment]
will take a look
