### ISSUE TITLE
ImportError: cannot import name 'AirLLMLlama2' from partially initialized module 'airllm' (most likely due to a circular import)

### ISSUE THREAD

**Issue by kw408** [lyogavin/Anima#74]
ImportError: cannot import name 'AirLLMLlama2' from partially initialized module 'airllm' (most likely due to a circular import)
遇到这么个错误，咋解？

**Comment by lyogavin** [comment]
Please don't run the code from inside the local code base. 

When you run `import airllm` from local code base it'll try to import the local airllm.py first, instead of import the one installed in pip install.
