### ISSUE TITLE
mistral模型无限加载中

### ISSUE THREAD

**Issue by fenglui** [lyogavin/Anima#83]
![1703165335399](https://github.com/lyogavin/Anima/assets/141198/35d49cb0-405f-4423-8bbe-65583f81a18d)

**Comment by lyogavin** [comment]
Some model for some prompt would generate very LONG text.

You can try either in generate() setting `max_new_token` to limit the length or setting `exponential_decay_length_penalty`. Check out more details [here](https://huggingface.co/docs/transformers/v4.36.1/en/main_classes/text_generation#transformers.GenerationConfig).

**Comment by fenglui** [comment]
thanks, set max_new_tokens to 5 and it works
